[package]
name = "advent2020"
version = "0.1.0"
authors = ["Arne Du√üin <arne.dussin@gmail.com>"]
edition = "2018"

[[bin]]
name = "01"
path = "src/01/main.rs"

[[bin]]
name = "02"
path = "src/02/main.rs"

[[bin]]
name = "03"
path = "src/03/main.rs"

[dependencies]
thiserror = "*"
